language: python
before_install:
  - docker pull buffepva/repositorg
  - docker create --name "repositorg" --rm -ti -v "${PWD}":/home/repositorg buffepva/repositorg
  - docker start repositorg
  - docker exec repositorg emaint sync -a
  # Re/Install newest dependencies:
  - docker exec repositorg sh -c '/home/repositorg/.gentoo/install.sh -o --autounmask-continue'
install:
  # Re/Install the package without tests, this is not separately needed as it is included in the script below:
  #- docker exec repositorg sh -c 'FEATURES="-test" /home/repositorg/.gentoo/install.sh --autounmask-continue'
script: 
  # Install and run tests (this is performed separately from dependency installation so as to not propagate the test FEATURE to the entire graph):
  - docker exec repositorg sh -c 'FEATURES="test" /home/repositorg/.gentoo/install.sh --autounmask-continue'
